using System.Runtime.InteropServices;

namespace Stroke.Input.Windows.Win32Types;

/// <summary>
/// Describes a keyboard input event in a console input record.
/// </summary>
/// <remarks>
/// <para>
/// Maps to the Windows KEY_EVENT_RECORD structure.
/// </para>
/// <para>
/// Thread safety: Immutable value type; inherently thread-safe.
/// </para>
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public readonly struct KeyEventRecord
{
    /// <summary>
    /// Non-zero if the key is pressed; zero if released.
    /// </summary>
    public readonly int KeyDown;

    /// <summary>
    /// Number of times the keystroke is repeated.
    /// </summary>
    public readonly ushort RepeatCount;

    /// <summary>
    /// Virtual-key code (Windows VK_* values).
    /// </summary>
    public readonly ushort VirtualKeyCode;

    /// <summary>
    /// Hardware scan code for the key.
    /// </summary>
    public readonly ushort VirtualScanCode;

    /// <summary>
    /// Unicode character generated by the key press.
    /// </summary>
    /// <remarks>
    /// This is a simplification of the native UNICODE_OR_ASCII union.
    /// .NET is natively Unicode, so the ASCII variant is omitted.
    /// </remarks>
    public readonly char UnicodeChar;

    /// <summary>
    /// State of control keys and toggle states.
    /// </summary>
    public readonly ControlKeyState ControlKeyState;

    /// <summary>
    /// Gets whether the key is pressed (vs. released).
    /// </summary>
    public bool IsKeyDown => KeyDown != 0;
}
